FROM node:16-alpine3.11

WORKDIR /src

RUN ls -al

ADD . .


# The docker-compose.dev and prod iles will append the actual command (dev or prod) 
# https://stackoverflow.com/a/62122648
ENTRYPOINT ["npm", "run"]
