FROM node:16-alpine3.11

WORKDIR /src

COPY package.json ./

RUN npm i --silent

ADD . .

ENV PORT=3001
EXPOSE 3001
# The docker-compose.dev and prod iles will append the actual command (dev or prod) 
# https://stackoverflow.com/a/62122648
ENTRYPOINT ["npm", "run"]
